import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import Header from "@/components/header/Header";
import Sidebar from "@/components/sidebar/Sidebar";
import IconSidebar from "@/components/sidebar/IconSidebar";
import Footer from "@/ui/Footer";
import CookieBanner from "@/ui/CookieBanner";
import CartSidebar from "@/components/sidebar/CartSidebar";
import CartOverlay from "@/ui/CartOverlay";
import ImageZoomOverlay from "@/ui/ImageZoomOverlay";
import ApplyTheme from "@/ui/ApplyTheme";
import LoadCart from "@/ui/LoadCart";
import Toast from "@/ui/Toast";
import Head from "next/head";
import { usePathname } from "next/navigation";

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: {
    template: "%s | Soner-MyShop",
    default: "Soner-MyShop",
  },
  // Generated by chatGPT
  description:
    "Willkommen bei MyShop, deinem One-Stop-Shop für alles, was du brauchst! Entdecke Elektronik, Mode, Haushaltswaren und mehr. Genieße eine einfache, sichere Einkaufserfahrung mit schnellen Lieferungen und exklusiven Angeboten!",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const baseUrl = "https://www.sonerapp.net";

  return (
    <html lang="de">
      <Head>
        <meta name="HandheldFriendly" content="true" />
        <link rel="canonical" href={`${baseUrl}${pathname}`} />
        <link rel="apple-touch-icon" href="./start-icon.png" />
      </Head>
      <body className={`${roboto.className} dark:bg-slate-900 dark:text-white`}>
        <StoreProvider>
          <Header />
          <Sidebar />
          <CookieBanner />
          <CartSidebar />
          <IconSidebar />
          <main className="duration-200 md:ml-20">{children}</main>
          <CartOverlay />
          <ImageZoomOverlay />
          <Footer />
          <LoadCart />
          <ApplyTheme />
          <Toast />
        </StoreProvider>
      </body>
    </html>
  );
}
