import { Metadata } from "next";
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: {
    template: "%s / Products",
    default: "Products",
  },

  // Generated by chatGPT
  description:
    "Discover the vast selection of products at ShopZilla. From electronics and fashion to household items, you'll find everything you're looking for – shop online conveniently and securely.",
};

export default function Layout({ children }: { children: ReactNode }) {
  return <section className="flex flex-col md:flex-row">{children}</section>;
}
