import { Metadata } from "next";
import { ReactNode } from "react";

export const metadata: Metadata = {
  // Generated by ChatGPT
  description:
    "Shop a wide range of products at MyShop. From electronics to fashion, find everything you need online with secure shopping.",
};

export default function Layout({ children }: { children: ReactNode }) {
  return <section>{children}</section>;
}
